import math

PEARL_GRAVITY_ACCELERATION: float = 0.03
PEARL_DRAG_MULTIPLIER: float = 0.99
PEARL_RADIUS: float = 0.125
PEARL_HEIGHT: float = 0.25
TNT_RADIUS: float = 0.49
TNT_HEIGHT: float = 0.98
TNT_EXPLOSION_RADIUS: float = 8.0
TNT_ENTITY_Y_OFFSET: float = 0.06125
PEARL_EXPLOSION_Y_FACTOR: float = 0.85
FLOAT_PRECISION_EPSILON: float = 1e-10